# Generated by Django 3.2 on 2021-05-11 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='year_in_school',
            field=models.CharField(choices=[('РЕШЕНО', 'РЕШЕНО'), ('В ОЖИДАНИИ ОТВЕТА', 'В ОЖИДАНИИ ОТВЕТА')], default='В ОЖИДАНИИ ОТВЕТА', max_length=200),
        ),
    ]
