# Generated by Django 3.2 on 2021-05-11 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_post_year_in_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='textqr',
            field=models.TextField(default='qr', max_length=1000),
        ),
    ]
