# Generated by Django 3.2 on 2021-05-11 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_post_textqr'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='textot',
            field=models.TextField(default='еще не ответили', max_length=1000),
        ),
    ]
